on:
  repository_dispatch:
    types:
      - elokey-deploy
jobs:
  deploy:
    strategy:
      matrix:
        platform:
          - ios
          - android
    runs-on: ${{matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest'}}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: qwezey/elokey
          token: ${{secrets.QWEZEY_BOT_TOKEN}}
          ref: ${{github.event.client_payload.ref}}
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-flutter
      - uses: ./.github/actions/setup-fastlane
        with:
          platform: ${{matrix.platform}}
      - run: ./scripts/deploy.ts
        env:
          PLATFORM: ${{matrix.platform}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          APP_STORE_CONNECT_API_KEY_JSON: ${{matrix.platform == 'ios' && secrets.APP_STORE_CONNECT_API_KEY_JSON}}
          MATCH_PASSWORD: ${{matrix.platform == 'ios' && secrets.MATCH_PASSWORD}}
