name: Traceit - Deploy Flutter App
on:
  workflow_dispatch:
    inputs:
      traceitRef:
        description: The branch or tag to deploy
        required: true
        default: main
      flavor:
        description: The flavor (aka environment) to deploy
        type: choice
        options:
          - dev
          - qa
jobs:
  deploy:
    strategy:
      matrix:
        platform: [android, ios]
    runs-on: ${{matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest'}}
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
        with:
          repository: qwezey/traceit
          token: ${{secrets.QWEZEY_BOT_TOKEN}}
          ref: ${{github.event.inputs.traceitRef}}

      # Get the build environment
      - run: ./scripts/get-build-environment.sh
        id: build-env

      # Install node and node dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: ${{steps.build-env.outputs.nodeVersion}}
          cache: npm
      - run: npm ci

      # Install flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{steps.build-env.outputs.flutterVersion}}
          channel: stable
          cache: true

      # Install ruby and fastlane dependencies
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{steps.build-env.outputs.rubyVersion}}
          bundler-cache: true
          working-directory: ${{matrix.platform}}

      # deploy the app to firebase
      - run: ./scripts/deploy-flutter-${{matrix.platform}}-app-to-firebase.ts
        env:
          FLAVOR: ${{github.event.inputs.flavor}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          APP_STORE_CONNECT_API_KEY_JSON: ${{matrix.platform == 'ios' && secrets.APP_STORE_CONNECT_API_KEY_JSON}}
          QWEZEY_BOT_TOKEN: ${{matrix.platform == 'ios' && secrets.QWEZEY_BOT_TOKEN}}
          MATCH_PASSWORD: ${{matrix.platform == 'ios' && secrets.MATCH_PASSWORD}}
