name: "Traceit - Deploy Flutter App"
on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        options:
          - dev
jobs:
  deploy:
    strategy:
      matrix:
        platform: [android, ios]
    runs-on: ${{matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest'}}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: qwezey/traceit
          token: ${{secrets.QWEZEY_BOT_TOKEN}}
          ref: work

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - run: ./scripts/get-build-environment.ts
        id: build-env

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{steps.build-env.outputs.flutterVersion}}
          channel: stable
          cache: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{steps.build-env.outputs.rubyVersion}}
          bundler-cache: true
          working-directory: ${{matrix.platform}}

      - run: ./scripts/deploy-flutter-${{matrix.platform}}-app-to-firebase.ts
        env:
          FLAVOR: ${{github.event.inputs.flavor}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          APP_STORE_CONNECT_API_KEY_JSON: ${{matrix.platform == 'ios' && secrets.APP_STORE_CONNECT_API_KEY_JSON}}
          QWEZEY_BOT_TOKEN: ${{matrix.platform == 'ios' && secrets.QWEZEY_BOT_TOKEN}}
          MATCH_PASSWORD: ${{matrix.platform == 'ios' && secrets.MATCH_PASSWORD}}
