name: "Traceit - Deploy Flutter App to Firebase"
on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        options:
          - dev
jobs:
  # android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         repository: qwezey/traceit
  #         token: ${{secrets.QWEZEY_BOT_TOKEN}}
  #         ref: work
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.16.0"
  #         channel: "stable"
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "18"
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: "3.2"
  #     - run: gem install fastlane --version 2.217.0
  #     - run: npm ci
  #     - run: npx ts-node ./scripts/deploy.ts
  #       env:
  #         PLATFORM: android
  #         BUNDLE_ID: com.qwezey.traceit.test
  #         QWEZEY_BOT_TOKEN: ${{secrets.QWEZEY_BOT_TOKEN}}
  #         MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
  #         APP_STORE_CONNECT_API_KEY: ${{secrets.APP_STORE_CONNECT_API_KEY}}
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: qwezey/traceit
          token: ${{secrets.QWEZEY_BOT_TOKEN}}
          ref: work
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: stable
          cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: ios
      - run: npm ci
      - run: ./scripts/deploy-flutter-ios-app-to-firebase.ts
        env:
          FLAVOR: ${{ github.event.inputs.flavor}}
          APP_STORE_CONNECT_API_KEY_JSON: ${{secrets.APP_STORE_CONNECT_API_KEY_JSON}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
          QWEZEY_BOT_TOKEN: ${{secrets.QWEZEY_BOT_TOKEN}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
