name: Traceit - Deploy Firebase Services
on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        options:
          - dev
      firestore:
        type: boolean
        default: true
      storage:
        type: boolean
        default: true
      extensions:
        type: boolean
        default: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: qwezey/traceit
          token: ${{secrets.QWEZEY_BOT_TOKEN}}
          ref: work

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
      - run: npm ci

      - run: ./scripts/deploy-firebase-services.ts
        env:
          FLAVOR: ${{ github.event.inputs.flavor }}
          DEPLOY_FIRESTORE: ${{ github.event.inputs.firestore }}
          DEPLOY_STORAGE: ${{ github.event.inputs.storage }}
          DEPLOY_EXTENSIONS: ${{ github.event.inputs.extensions }}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
